image: docker:dind

stages:
  - build
  - test
  - release
  - deploy

variables:
  CONTAINER_IMAGE: registry.gitlab.com/libreborme/libreborme
  CONTAINER_TEST_IMAGE: $CONTAINER_IMAGE:$CI_BUILD_REF_NAME
  DEPLOY_PATH: /opt/libreborme

build:
  stage: build
  tags:
    - kubernetes
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
    - cd docker/nginx && docker build -t registry.gitlab.com/libreborme/libreborme/nginx:$CI_BUILD_REF_NAME .
    - docker push registry.gitlab.com/libreborme/libreborme/nginx:$CI_BUILD_REF_NAME

test:
  stage: test
  tags:
    - kubernetes
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $CONTAINER_TEST_IMAGE
    - docker-compose -f docker-compose.ci.yml -p ci up --abort-on-container-exit
  coverage: '/TOTAL.*?(\d{1,2}.\d+%)/'


release_stg:
  stage: release
  tags:
    - kubernetes
  only:
    - staging
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_IMAGE:staging
    - docker push $CONTAINER_IMAGE:staging
    - docker tag registry.gitlab.com/libreborme/libreborme/nginx:$CI_BUILD_REF_NAME registry.gitlab.com/libreborme/libreborme/nginx:staging
    - docker push registry.gitlab.com/libreborme/libreborme/nginx:staging

deploy_stg:
  stage: deploy
  tags:
    - kubernetes
  only:
    - staging
  environment:
    name: staging
    url: http://staging.ingress.libreborme.net
  script:
    - echo "Hello"
    - kubectl set image deployment/libreborme libreborme-container=libreborme:staging
    - kubectl rollout status deployment/libreborme
