stages:
  - build
  - test
  - release
  - deploy

variables:
  CONTAINER_IMAGE: registry.gitlab.com/libreborme/libreborme
  CONTAINER_TEST_IMAGE: $CONTAINER_IMAGE:$CI_BUILD_REF_NAME
  DEPLOY_PATH: /opt/libreborme

build:
  stage: build
  tags:
    - shell
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
    - cd docker/nginx && docker build -t registry.gitlab.com/libreborme/libreborme/nginx:$CI_BUILD_REF_NAME .
    - docker push registry.gitlab.com/libreborme/libreborme/nginx:$CI_BUILD_REF_NAME

test:
  stage: test
  tags:
    - shell
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $CONTAINER_TEST_IMAGE
    - docker-compose -f docker-compose.ci.yml -p ci up --abort-on-container-exit
  coverage: '/TOTAL.*?(\d{1,2}.\d+%)/'


release_stg:
  stage: release
  tags:
    - shell
  only:
    - staging
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_IMAGE:staging
    - docker push $CONTAINER_IMAGE:staging
    - docker tag registry.gitlab.com/libreborme/libreborme/nginx:$CI_BUILD_REF_NAME registry.gitlab.com/libreborme/libreborme/nginx:staging
    - docker push registry.gitlab.com/libreborme/libreborme/nginx:staging


deploy_stg:
  stage: deploy
  variables:
    DOCKER_CERT_PATH: ~/.docker
    # DOCKER_CERT_PATH: ~/.docker/machine/certs/
    DOCKER_HOST: tcp://142.93.228.30:2376
    DOCKER_TLS_VERIFY: 1
    SERVICE_NAME: libreborme
  tags:
    - shell
  only:
    - staging
  environment:
    name: staging
    url: http://beta.libreborme.net
  script:
    - mkdir -p $DOCKER_CERT_PATH
    - echo "$TLSCACERT" > $DOCKER_CERT_PATH/ca.pem
    - echo "$TLSCERT" > $DOCKER_CERT_PATH/cert.pem
    - echo "$TLSKEY" > $DOCKER_CERT_PATH/key.pem
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker stack deploy --with-registry-auth --compose-file=docker-compose.staging.yml ${SERVICE_NAME}
