language: python
python:
  - "3.4"
  - "3.6"

addons:
  postgresql: "9.4"

services:
  - postgresql

env:
  - DJANGO_VERSION=2.0.4 ES_VERSION=5.6.9 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz

install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
  - pip install coveralls
  - pip install -r requirements/development.txt
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q develop

before_script:
  - psql -U postgres -c 'CREATE DATABASE libreborme;'
  - psql -U postgres -c "CREATE USER libreborme WITH PASSWORD 'password';"
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE libreborme TO libreborme;"
  - ./manage.py migrate --noinput

script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - ./setup.py test

after_success:
  - coveralls
