branches:
  only:
    - master
    - develop

language: python

services:
    - mongodb

python:
  - "3.4"

install:
#  - pip install coveralls
  - pip install -r requirements/test.txt
  - pip install django-extensions
  - python setup.py -q develop
  - mkdir -p ~/.bormes/pdf/2015/02/10
  - wget http://www.boe.es/borme/dias/2015/02/10/pdfs/BORME-A-2015-27-10.pdf -O ~/.bormes/pdf/2015/02/10/BORME-A-2015-27-10.pdf

before_script:
#  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

# command to run tests, e.g. python setup.py test
#script:
#  - coverage run --source=libreborme setup.py test
script: "./runtests.sh"

#after_success:
#  - coveralls
