branches:
  only:
    - master
    - develop

language: python

services:
    - postgresql
    - elasticsearch

python:
  - "3.4"
  - "3.5"

install:
#  - pip install coveralls
  - pip install -r requirements/test.txt
  - pip install django-extensions
  - pip install "Django${DJANGO_VERSION}"
  - python setup.py -q develop
  - mkdir -p ~/.bormes/pdf/2015/02/10
  - wget https://www.boe.es/borme/dias/2015/02/10/pdfs/BORME-A-2015-27-10.pdf -O ~/.bormes/pdf/2015/02/10/BORME-A-2015-27-10.pdf

before_script:
  - sleep 10  # Elasticsearch
  - psql template1 -c 'CREATE EXTENSION hstore;'
  - psql -U postgres -c 'CREATE DATABASE libreborme;'
  - psql -U postgres -c "CREATE USER libreborme WITH PASSWORD 'password';"
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE libreborme TO libreborme;"
  - ./manage.py migrate --noinput

# command to run tests, e.g. python setup.py test
#script:
#  - coverage run --source=libreborme setup.py test
script: "./runtests.sh"

env:
    matrix:
        - DJANGO_VERSION=">=1.8,<1.9"
        - DJANGO_VERSION=">=1.9,<1.10"

#after_success:
#  - coveralls
