language: python
python:
  - "3.4"
  - "3.6"

addons:
  postgresql: "9.4"

services:
  - postgresql

env:
  - DJANGO_VERSION=2.0.4

install:
  - pip install coveralls
  - pip install -r requirements/development.txt
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q develop

before_script:
  - sleep 10  # Elasticsearch
  - psql -U postgres -c 'CREATE DATABASE libreborme;'
  - psql -U postgres -c "CREATE USER libreborme WITH PASSWORD 'password';"
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE libreborme TO libreborme;"
  - ./manage.py migrate --noinput

script:
  - ./setup.py test

after_success:
  - coveralls
