---
version: "3.4"

services:

  nginx:
    # image: registry.gitlab.com/libreborme/libreborme/nginx:staging
    build: ./docker/nginx
    depends_on:
      - app
    #    healthcheck:
    #      test: ["CMD", "curl", "-f", "http://localhost"]
    #      interval: 1m30s
    #      timeout: 10s
    #      retries: 3
    #      start_period: 40s
    ports:
      - "80:80"
    volumes:
      - /opt/libreborme/static:/static:ro
      # Logs don't show up in docker if the volume is mounted
      # - /opt/libreborme/log/nginx:/var/log/nginx/
      - /opt/libreborme/run:/run
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - public
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == staging-node-1]

  app:
    # image: registry.gitlab.com/libreborme/libreborme:staging
    build: .
    command: make staging settings=libreborme.settings_staging
    depends_on:
      - postgres
      - elasticsearch
    ports:
      - "8000:8000"
    volumes:
      - /opt/libreborme/static:/static
      - /opt/libreborme/run:/opt/libreborme/run
      - /opt/libreborme/bormes:/opt/libreborme/bormes
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - public
      - internal
    environment:
      DJANGO_SETTINGS_MODULE: libreborme.settings_staging
      ENV_TYPE: staging
      ELASTICSEARCH_URI: http://elastic:changeme@elasticsearch:9200
      RAVEN_DSN: https://d0c18e5df3ac420a89014b9e0dafdd55@sentry.io/1290035
      DB_HOST: postgres
      DB_PORT: 5432
      PIWIK_URL: ""
      PIWIK_SITE_ID: ""
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == staging-node-1]

  postgres:
    # restart: always
    image: postgres:9.5
    volumes:
      - db-data:/var/lib/postgresql
      # Django wants postgres database to be UTC
      # - /etc/localtime:/etc/localtime:ro
      # - /etc/timezone:/etc/timezone:ro
    networks:
      - internal
    environment:
      POSTGRES_DB: libreborme
      POSTGRES_USER: libreborme
      POSTGRES_PASSWORD: password
    deploy:
      placement:
        constraints: [node.hostname == staging-node-2]

  elasticsearch:
    # restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.15
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - internal
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    deploy:
      placement:
        constraints: [node.hostname == staging-node-2]

volumes:
  db-data:
  es-data:

networks:
  public:
  internal:
