---
version: "3.4"

services:
  db:
    image: postgres:9.5
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: libreborme

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"

#  django:
#    build: docker/Dockerfile
#    ports:
#     - "8000:8000"
#    links:
#     - db
#    environment:
#     - ENV_TYPE: development

volumes:
  db-data:
  es-data:
