---
version: "3.4"

services:

  app:
    image: ${CONTAINER_IMAGE}:${CI_BUILD_REF_NAME}
    command: bash -c "make test_ci"
    # coverage vs coveralls?
    depends_on:
      - postgres
      - elasticsearch
    environment:
      DJANGO_SETTINGS_MODULE: libreborme.settings_ci
      ENV_TYPE: ci
      ELASTICSEARCH_URI: http://elasticsearch:9200

  postgres:
    restart: always
    image: postgres:9.5
    environment:
      POSTGRES_DB: libreborme
      POSTGRES_USER: libreborme
      POSTGRES_PASSWORD: password

  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
