---
version: "3"

services:

  app:
    image: ${CONTAINER_IMAGE}:${CI_BUILD_REF_NAME}
    command: bash -c "sleep 8 && coverage run --source='.' manage.py test -v 3 && coverage report"
    depends_on:
      - postgresql
      - elasticsearch
    depends_on:
      - postgresql
      - elasticsearch
    environment:
      DJANGO_SETTINGS_MODULE: libreborme.settings_ci
      ENV_TYPE: development
      ELASTICSEARCH_URI: http://elasticsearch:9200

  postgresql:
    restart: always
    image: postgres:9.5
    environment:
      POSTGRES_DB: libreborme
      POSTGRES_USER: libreborme
      POSTGRES_PASSWORD: password

  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
