site_name: Documentación de libreborme
site_description: Documentación de libreborme
site_author: Pablo Castellano
copyright: © Copyright 2015, Pablo Castellano
repo_url: https://github.com/PabloCastellano/libreborme/
pages:
- ¡Bienvenido a la documentación de LibreBorme!: index.md
- Acerca de LibreBORME: introduction.md
- Instalación manual: installation.md
- Instalación automática: install_production_automated.md
- Comandos de LibreBorme: commands.md
- API: api.md
theme: readthedocs
