apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: libreborme-daily-import
spec:
  schedule: "0 8 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: libreborme-daily-import
              image: registry.gitlab.com/libreborme/libreborme:staging
              args:
                - /bin/sh
                - -c
                - date; ./manage.py importbormetoday
              env:
                - name: DJANGO_SETTINGS_MODULE
                  value: libreborme.settings_staging
                - name: ENV_TYPE
                  value: staging
                - name: ELASTICSEARCH_URI
                  value: http://elastic:changeme@elasticsearch:9200
                - name: RAVEN_DSN
                  value: https://d0c18e5df3ac420a89014b9e0dafdd55@sentry.io/1290035
                - name: DB_HOST
                  value: postgres
                - name: DB_PORT
                  value: "5432"
                - name: PIWIK_URL
                  value: "http://"
                - name: PIWIK_SITE_ID
                  value: "5"
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 5
