kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:5.6.15
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: -Xms256m -Xmx512m
          ports:
            - containerPort: 9200
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
#           - mountPath: /usr/share/elasticsearch/data
#             name: es-data
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Europe/Madrid
#       - name: es-data
#         persistentVolumeClaim:
#           claimName: elasticsearch-pv-claim
