kind: Service
apiVersion: v1
metadata:
  name: libreborme-nginx
spec:
  selector:
    app: libreborme
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: libreborme
  labels:
    app: libreborme
    track: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: libreborme
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: libreborme
    spec:
      containers:
        - name: nginx
          image: nginx:1.15-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
              httpHeaders:
                - name: Host
                  value: staging.ingress.libreborme.net
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
              httpHeaders:
                - name: Host
                  value: staging.ingress.libreborme.net
            initialDelaySeconds: 10
            timeoutSeconds: 1
          volumeMounts:
            - name: "nginx-conf"
              mountPath: "/etc/nginx/conf.d"
            - name: "staticfiles"
              mountPath: "/opt/libreborme/static"
            - name: tz-config
              mountPath: /etc/localtime
        - name: libreborme
          image: registry.gitlab.com/libreborme/libreborme:staging
          imagePullPolicy: Always
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: libreborme.settings_staging
            - name: ENV_TYPE
              value: staging
            - name: ELASTICSEARCH_URI
              value: http://elastic:changeme@elasticsearch:9200
            - name: RAVEN_DSN
              value: https://d0c18e5df3ac420a89014b9e0dafdd55@sentry.io/1290035
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: PIWIK_URL
              value: "http://"
            - name: PIWIK_SITE_ID
              value: "5"
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
              httpHeaders:
                - name: Host
                  value: staging.ingress.libreborme.net
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 1
          volumeMounts:
            - name: staticfiles
              mountPath: "/opt/libreborme/static"
            - name: tz-config
              mountPath: /etc/localtime
          # add settings.py here as secret configmap
      imagePullSecrets:
        - name: "registry.gitlab.com"
      volumes:
        - name: "nginx-conf"
          configMap:
            name: "nginx-libreborme"
            items:
              - key: "libreborme.conf"
                path: "libreborme.conf"
        - name: "staticfiles"
          emptyDir: {}
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Europe/Madrid
